package synanton.extraction.spi.model;

/**
 * How an element's content was obtained. {@code GENERATED} means LLM/VLM produced;
 * NOT source evidence (rule §67.10).
 */
public enum ContentOrigin {

    /** The text was extracted directly from embedded character-level content. */
    EMBEDDED_TEXT,

    /** The text was obtained via optical character recognition. */
    OCR,

    /** The structure was derived from a tagged or structured format (e.g. PDF tags, DOCX XML). */
    TAGGED_STRUCTURE,

    /** The layout was inferred from visual positioning heuristics. */
    LAYOUT_INFERRED,

    /**
     * The content was generated by a language or vision-language model.
     * This is NOT source evidence (rule §67.10).
     */
    GENERATED,

    /** The content was obtained via audio/video transcription. */
    TRANSCRIBED
}
